import React from "react";
import type { EvidenceReport } from "./EvidenceTypes";
import { label } from "./Common";

export function CoverageView({ report }: { report: EvidenceReport }) {
  return <section className="columns">
    <section className="panel"><h2>Provenance</h2><article className="compact"><b>Engine {report.provenance.engine.version}</b><p>Build {report.provenance.engine.build_revision ?? "unavailable"}</p><small>Policy {report.provenance.detector_policy_hash}<br />Config {report.provenance.configuration.hash}</small></article><article className="compact"><b>Target source</b><p>{report.provenance.source.git_revision ?? "non-Git directory"}</p><small>{report.provenance.source.dirty == null ? "dirty state unavailable" : report.provenance.source.dirty ? "dirty working tree" : "clean working tree"}</small></article></section>
    {report.baseline_comparison && <section className="panel"><h2>Baseline comparison</h2><article className="compact"><b>{report.baseline_comparison.baseline_path ?? "workflow baseline"}</b><p>{report.baseline_comparison.findings.added.length} added · {report.baseline_comparison.findings.removed.length} removed · {report.baseline_comparison.findings.changed.length} changed · {report.baseline_comparison.findings.unchanged_count} unchanged findings</p><small>Origins: {report.baseline_comparison.provenance_change_dimensions.join(", ") || "unknown"}</small></article>{report.baseline_comparison.lineage_candidates.map(candidate => <article className="compact" key={candidate.id}><b>{candidate.id} · {candidate.confidence_percent}%</b><p>{candidate.previous_id} → {candidate.current_id}</p><small>{candidate.reasons.join(" · ")}</small></article>)}</section>}
    <section className="panel"><h2>Data-flow coverage</h2><article className="compact"><b>Status</b><span className={`status ${report.flow_analysis.status}`}>{label(report.flow_analysis.status)}</span><p>{report.flow_analysis.functions_analyzed} Rust functions · {report.flow_analysis.exact_edges} exact edges · {report.flow_analysis.unresolved_edges} unresolved · {report.flow_analysis.truncated_paths} truncated paths</p></article>{report.flow_analysis.capabilities.map(capability => <article className="compact" key={capability.language}><b>{label(capability.language)}</b><p>Local def-use: {label(capability.local_def_use)} · direct calls: {label(capability.direct_calls)} · fields: {label(capability.fields)} · dispatch: {label(capability.dynamic_dispatch)} · library models: {label(capability.library_models)}</p>{capability.reasons.map(reason => <small key={reason}>{reason}</small>)}</article>)}</section>
    <section className="panel"><h2>Coverage audit</h2>{report.coverage_manifest.map(cell => <article className="compact" key={`${cell.mechanism}-${cell.entity_scope}`}><b>{label(cell.mechanism)} · {label(cell.entity_scope)}</b><span className={`status ${cell.status}`}>{label(cell.status)}</span><p>{cell.reason}</p><small>{cell.completed_detectors.length}/{cell.detectors.length} detectors completed · {cell.entity_count} entities</small></article>)}</section>
    <section className="panel"><h2>Detector receipts</h2>{report.detector_execution.map(item => <article className="compact" key={item.kind}><b>{label(item.kind)}</b><span>{label(item.status)}</span><p>{item.observations.map(observation => `${label(observation.stage)}: ${observation.count} ${label(observation.unit)}`).join(" · ") || "no applicable inputs"}</p><small>{item.candidate_groups_before_threshold} pre-threshold groups · {item.raw_emitted} emitted − {item.cli_filtered} filtered − {item.suppression_removed} suppressed = {item.final_findings} final · {item.unobservable_count} unobservable</small></article>)}</section>
  </section>;
}
