export type Percentiles = { p50: number; p75: number; p90: number; p95: number; max: number };
export type ChurnFileMetric = { commits_touched: number; lines_added: number; lines_deleted: number; authors_count: number; recent_weighted_churn: number };
export type FileRawMetric = { path: string; loc: number; imports: number; public_items: number; is_test: boolean; churn: ChurnFileMetric };
export type LocatedRawMetric = Record<string, unknown> & { path: string; name?: string; line?: number };
export type FindingMetric = { name: string; value: number; threshold?: number | null; excess_ratio?: number | null; unit: string; normalized?: number | null; percentile?: number | null };
export type RelatedLocation = { path: string; line: number; name?: string | null };
type FlowLocation = { id: string; kind: string; path: string; line: number; function: string; module: string; name: string };
type FlowWitnessStep = { kind: string; resolution: string; from: string; to: string; path: string; line: number; name: string };
type FlowWitness = { policy: string; source: FlowLocation; ordered_steps: FlowWitnessStep[]; sink: FlowLocation; module_hops: number; call_edges: number; path_steps: number; truncated: boolean; conforming_path?: RelatedLocation[] | null };
export type Finding = { id: string; kind: string; path: string; line?: number | null; metrics: FindingMetric[]; construct: string; mechanism: string; issue_id?: string | null; message: string; recommendation: string; related_locations: RelatedLocation[]; flow_witness?: FlowWitness | null };
export type Issue = { id: string; family: string; summary: string; construct: string; mechanism: string; action: string; path: string; line?: number | null; primary_finding_id: string; finding_ids: string[]; kinds: string[]; subject: Record<string, unknown> };
export type DependencyGraphNode = { path: string; fan_in: number; fan_out: number };
export type DependencyGraphEdge = { from: string; to: string };
export type AgentTestReachability = { direct_test_files: string[]; reachable_test_files: string[]; reachable_test_file_count: number; nearest_test_distance?: number | null; nearest_test_paths: string[]; paths_truncated: boolean };
export type FileAgentEvidence = AgentTestReachability & { path: string; coverage_status: string; context_closure_files: number; context_closure_loc: number; unresolved_local_dependencies: number };
export type IssueAgentEvidence = AgentTestReachability & { issue_id: string; coverage_status: string; evidence_dispersion: { evidence_files: string[]; evidence_directories: string[]; evidence_languages: string[] }; context_closure_files: number; context_closure_loc: number; unresolved_local_dependencies: number };
export type CoverageCell = { mechanism: string; entity_scope: string; expectation: string; status: string; reason: string; detectors: string[]; completed_detectors: string[]; entity_count: number; unobservable_reasons: string[] };
export type DetectorExecutionReceipt = { kind: string; status: string; analyzed_entities: number; candidate_groups: number; unobservable_count: number; unobservable_reasons: string[] };
export type RawMetricCoverage = { metric: string; status: string; entity_count: number; reason: string; unobservable_reasons: string[] };
export type DetectorManifestEntry = { kind: string; construct: string; mechanism: string; action: string; entity_scope: string; approach: string; supported_languages: string[]; precision_risk: string; input_metrics: string[]; issue_family: string; evidence_role: string; constituent_kinds: string[] };
export type RawMetricManifestEntry = { name: string; entity_scope: string; unit: string; scale: string; direction: string; description: string };
export type ChurnSummary = { mode: string; enabled: boolean; status: string; reason?: string | null; window_days: number; max_commit_lines: number };
export type ScanSummary = { scanned_files: number; finding_count: number; issue_count: number; similar_function_group_count: number; duration_ms: number; churn: ChurnSummary };
export type ScanStats = { source_files_scanned: number; directories_scanned: number; function_candidates: number };
export type RawMetrics = { directories: LocatedRawMetric[]; files: FileRawMetric[]; functions: LocatedRawMetric[]; types: LocatedRawMetric[] };
export type DependencyGraph = { nodes: DependencyGraphNode[]; edges: DependencyGraphEdge[] };
export type AgentEvidence = { files: FileAgentEvidence[]; issues: IssueAgentEvidence[] };
export type SuppressionSummary = { suppressed_count: number; suppressed_by_kind: Record<string, number> };
export type CoverageSummary = { detected_languages?: string[]; unobservable_reasons?: string[]; parse_failures?: unknown[]; unresolved_dependency_edges?: number };
type FlowCapability = { language: string; local_def_use: string; direct_calls: string; fields: string; dynamic_dispatch: string; library_models: string; reasons: string[] };
type FlowAnalysis = { status: string; functions_analyzed: number; exact_edges: number; unresolved_edges: number; truncated_paths: number; capabilities: FlowCapability[] };

export type ScanReport = {
  schema_version: number;
  summary: ScanSummary;
  stats: ScanStats;
  metrics_summary: Record<string, Record<string, Percentiles>>;
  raw_metrics: RawMetrics;
  raw_metric_manifest: RawMetricManifestEntry[];
  dependency_graph: DependencyGraph;
  agent_evidence: AgentEvidence;
  unity_project: Record<string, unknown>;
  suppression_summary: SuppressionSummary;
  flow_analysis: FlowAnalysis;
  coverage_manifest: CoverageCell[];
  coverage_summary: CoverageSummary;
  detector_execution: DetectorExecutionReceipt[];
  raw_metric_coverage: RawMetricCoverage[];
  issues: Issue[];
  detector_manifest: DetectorManifestEntry[];
  findings: Finding[];
};
