use super::CommentKind;

const PROTECTION_MARKERS: &[(&str, &[&str])] = &[
    (
        "license",
        &[
            "copyright",
            "spdx",
            "license",
            "licence",
            "all rights reserved",
            "permission is hereby granted",
        ],
    ),
    (
        "tool_directive",
        &[
            "reforge:",
            "#!",
            "coding:",
            "coding=",
            "noqa",
            "type: ignore",
            "pyright:",
            "mypy:",
            "pylint:",
            "ruff:",
            "fmt:",
            "go:",
            "+build",
            "nolint",
            "shellcheck",
            "#requires",
            "#pragma",
            "rubocop:",
            "frozen_string_literal:",
            "typed:",
            "swiftlint",
            "swiftformat",
            "clang-format",
            "clang-tidy",
            "nosemgrep",
            "coverage:",
            "sqlfluff:",
            "yamllint",
            "stylelint",
            "ignore_for_file:",
            "eslint",
            "prettier",
            "tslint",
            "@",
            "istanbul",
            "c8 ",
            "v8 ignore",
            "sourceurl",
            "sourcemappingurl",
            "webpack",
            "vite-ignore",
            "#__",
            "# source",
            "jshint",
            "jslint",
            "biome",
            "deno-lint",
            "region",
            "rustfmt",
            "noinspection",
            "language=",
            "<reference",
            "#if",
            "#else",
            "#endif",
        ],
    ),
    ("declared_debt", &["todo", "fixme", "xxx", "hack"]),
    (
        "rationale_or_constraint",
        &[
            "safety",
            "unsafe",
            "because",
            "reason:",
            "rationale",
            "invariant",
            "workaround",
            "must ",
            "do not",
            "don't",
            "why:",
            "原因",
            "安全",
            "必须",
            "不要",
            "兼容",
        ],
    ),
    (
        "generated_notice",
        &[
            "generated",
            "do not edit",
            "autogenerated",
            "auto-generated",
        ],
    ),
];

pub(super) fn protections(kind: CommentKind, text: &str) -> Vec<String> {
    let mut reasons = Vec::new();
    if kind == CommentKind::Documentation {
        reasons.push("documentation".into());
    }
    let lower = text.to_lowercase();
    for (reason, markers) in PROTECTION_MARKERS {
        if markers.iter().any(|marker| lower.contains(marker)) {
            reasons.push((*reason).into());
        }
    }
    reasons
}

pub(super) fn suggestions(content: &str, occurrences: usize) -> Vec<String> {
    let mut suggestions = Vec::new();
    if content
        .chars()
        .all(|c| c.is_whitespace() || "-=*_~".contains(c))
    {
        suggestions.push("empty_or_separator".into());
    }
    if content.len() >= 12 && occurrences > 1 {
        suggestions.push("repeated_text_in_file".into());
    }
    let lower = content.to_lowercase();
    if [
        "your code here",
        "insert code here",
        "implementation goes here",
        "add implementation here",
    ]
    .iter()
    .any(|text| lower.contains(text))
    {
        suggestions.push("template_placeholder".into());
    }
    if content.lines().any(possible_code) {
        suggestions.push("possible_commented_code".into());
    }
    suggestions
}

fn possible_code(line: &str) -> bool {
    let line = line.trim();
    [
        "let ",
        "const ",
        "var ",
        "return ",
        "fn ",
        "function ",
        "import ",
        "use ",
    ]
    .iter()
    .any(|prefix| line.starts_with(prefix))
        && (line.ends_with(';') || line.ends_with('{') || line.ends_with('}'))
}
