export const copy = {
  en: {
    language: "Language", docs: "Documentation", heroLabel: "Interactive walkthrough", headline: "Review an Agent change.",
    intro: "A coding Agent can finish the task in front of it while missing patterns elsewhere in the repository. Reforge turns those repository-level conflicts into evidence a reviewer can inspect.",
    startReview: "Choose a sample change ↓", fixtureNote: "These are small, built-in fixtures—not your repository. Nothing is uploaded.",
    contextLabel: "What you are about to do", contextTitle: "Simulate one pull-request review",
    contextBody: "Imagine a maintainer gave a coding Agent a small feature request. The patch looks reasonable and may even work. Your job is to check whether it still fits the repository around it.",
    contextInput: "Read the request and patch", contextInputHint: "See exactly what the Agent was asked to change.",
    contextAnalysis: "Compare it with the repository", contextAnalysisHint: "Reforge analyzes existing boundaries, abstractions, and dependencies.",
    contextOutput: "Inspect the evidence", contextOutputHint: "Decide whether the change should be revised before merge.",
    chooseLabel: "Built-in sample repositories", scenarios: "Which change do you want to review?", scenarioHelp: "Pick a task below. We will show the Agent's patch first, then reveal what Reforge found in the surrounding repository.", openExample: "Review this change",
    selected: "Reviewing", nowReviewing: "Scenario context", howToRead: "How to read this example", readTask: "Understand the task", readTaskHint: "What was requested and what the repository already does",
    readPatch: "Inspect the patch", readPatchHint: "What the agent added or changed", readEvidence: "Follow the evidence", readEvidenceHint: "Why the local change conflicts with the wider repository",
    maintainerTask: "The request", agentChose: "The agent's decision", repositoryExpects: "The existing pattern", reforgeObserved: "What Reforge found", reviewResult: "Follow the evidence",
    generatedEvidence: "Real analyzer output", loadingReport: "Loading analyzer output…", evidenceShape: "Why Reforge flagged it", reportFacts: "Analyzer facts",
    technicalDetails: "Technical details", openReport: "Open the complete generated report", agentPatch: "Inspect the patch", patch: "Patch",
    repositoryContext: "Repository context", fullSource: "Full source", configuration: "Config", reproduce: "Command",
    commandNote: "Run from the Reforge repository after building the CLI.", footer: "Repository-owned fixtures. Real schema 27 reports. No uploads.",
    reportError: "The generated report could not be loaded. Patch, repository context, configuration, and local reproduction remain available.",
    threshold: "threshold", coverage: "coverage", exactWitness: "Exact ordered witness", source: "Source", sink: "Sink", step: "Step",
    implementationGroup: "Implementations grouped by the report", dependencyLoop: "Reported cycle members", beforeDirection: "Before: one-way dependency", afterDirection: "After: closed loop",
  },
  "zh-CN": {
    language: "语言", docs: "文档", heroLabel: "交互式演示", headline: "审查一次 Agent 变更。",
    intro: "Coding Agent 可以完成眼前的任务，却看漏仓库其他位置已经形成的模式。Reforge 把这些仓库级冲突变成 Reviewer 可以核查的证据。",
    startReview: "选择一份示例变更 ↓", fixtureNote: "这里使用内置的小型 fixture，不是你的仓库；不会上传任何代码。",
    contextLabel: "接下来要做什么", contextTitle: "模拟一次 Pull Request 审查",
    contextBody: "设想维护者把一个小功能交给 Coding Agent。Patch 看起来合理，甚至可以正常工作；你的任务是确认它放回整个仓库后是否仍然合适。",
    contextInput: "阅读任务与 Patch", contextInputHint: "先看 Agent 收到了什么任务，具体改了什么。",
    contextAnalysis: "与现有仓库比较", contextAnalysisHint: "Reforge 分析已有边界、抽象和依赖关系。",
    contextOutput: "核查分析证据", contextOutputHint: "据此判断这份变更是否应该在合并前调整。",
    chooseLabel: "内置示例仓库", scenarios: "你想审查哪一份变更？", scenarioHelp: "选择一个任务。我们会先展示 Agent 的 Patch，再揭示 Reforge 在周边仓库中发现了什么。", openExample: "审查这份变更",
    selected: "审查中", nowReviewing: "场景背景", howToRead: "如何阅读这个示例", readTask: "理解任务", readTaskHint: "任务要求什么，仓库原本怎么做",
    readPatch: "查看 Patch", readPatchHint: "Agent 新增或修改了什么", readEvidence: "跟随证据", readEvidenceHint: "为什么局部改动与整个仓库发生冲突",
    maintainerTask: "任务要求", agentChose: "Agent 的实现选择", repositoryExpects: "仓库原有模式", reforgeObserved: "Reforge 的发现",
    reviewResult: "跟随证据", generatedEvidence: "真实分析器输出", loadingReport: "正在载入分析器输出…", evidenceShape: "Reforge 为什么标记它", reportFacts: "分析器字段",
    technicalDetails: "技术细节", openReport: "打开完整生成报告", agentPatch: "查看 Patch", patch: "Patch",
    repositoryContext: "Repository context", fullSource: "Full source", configuration: "Config", reproduce: "Command",
    commandNote: "构建 CLI 后，从 Reforge 仓库根目录运行。", footer: "仓库自有 fixture、真实 schema 27 报告、不上传代码。",
    reportError: "无法载入生成的报告，但 patch、仓库上下文、配置和本地复现命令仍然可用。",
    threshold: "阈值", coverage: "覆盖", exactWitness: "精确有序 witness", source: "源点", sink: "汇点", step: "步骤",
    implementationGroup: "报告归组的实现", dependencyLoop: "报告中的闭环成员", beforeDirection: "修改前：单向依赖", afterDirection: "修改后：形成闭环",
  },
};

export const scenarios = {
  "typescript-service-bypass": {
    language: "TypeScript", analysis: "Dataflow", rule: "reforge.dataflow.adapter_flow_bypass", visualization: "witness",
    beforeFiles: ["src/user_route.ts", "src/user_service.ts", "src/database.ts"],
    afterFiles: ["src/user_route.ts", "src/user_search_route.ts", "src/user_service.ts", "src/database.ts"],
    contextFiles: ["src/user_route.ts", "src/user_service.ts", "src/database.ts"], entry: "src/user_search_route.ts",
    en: {
      title: "Bypasses the service layer", card: "A new route queries the database directly", change: "Add a user search endpoint",
      setup: "A small API already sends user requests through a service layer. The new endpoint needs to look up a user by ID.",
      task: "Add an endpoint that looks up a user by ID.", chose: "Called queryUser directly from the new route.",
      expects: "HTTP routes call user_service before reaching the database module.",
      observed: "An exact value path reaches the database without crossing user_service.",
      explanation: "The endpoint works in isolation, but it creates a second route to the database and bypasses the repository's existing service boundary.",
      context: "Repository context (not a report field): the existing user route reaches database through user_service.",
    },
    "zh-CN": {
      title: "绕过 Service 层", card: "新 Route 直接查询数据库", change: "新增用户查询接口",
      setup: "一个小型 API 已经通过 Service 层处理用户请求。现在需要增加一个按 ID 查询用户的接口。",
      task: "增加一个按 ID 查询用户的接口。", chose: "在新的 Route 中直接调用 queryUser。",
      expects: "HTTP Route 先调用 user_service，再访问 database 模块。",
      observed: "一条精确值流路径没有经过 user_service，直接到达 database。",
      explanation: "这个接口单独看可以工作，却为数据库创建了第二条访问路径，绕过了仓库已有的 Service 边界。",
      context: "仓库上下文（并非报告字段）：已有用户 Route 通过 user_service 访问 database。",
    },
  },
  "python-duplicated-validation": {
    language: "Python", analysis: "Codebase", rule: "reforge.codebase.shadowed_abstraction", visualization: "group",
    beforeFiles: ["forms/legacy_email_validator.py", "shared/email_validator.py"],
    afterFiles: ["forms/legacy_email_validator.py", "forms/signup_email_validator.py", "shared/email_validator.py"],
    contextFiles: ["shared/email_validator.py", "forms/legacy_email_validator.py"], entry: "forms/signup_email_validator.py",
    en: {
      title: "Duplicates shared validation", card: "A third email validator appears", change: "Validate a signup form",
      setup: "A web app needs email validation on its new signup form. The repository already has a shared validator and one legacy local copy.",
      task: "Validate the email field on the signup form.", chose: "Copied the legacy form's local validate_email function.",
      expects: "Forms use the validator owned by shared/email_validator.py.",
      observed: "The shared implementation and two form-local functions form one shadowed-abstraction group.",
      explanation: "The Agent followed nearby code, but repository-wide evidence shows that this creates a third implementation of validation already owned by shared/email_validator.py.",
      context: "Repository context: a shared validator already exists alongside one legacy local implementation; two copies remain below the detector threshold.",
    },
    "zh-CN": {
      title: "重复共享校验逻辑", card: "出现第三份邮箱校验函数", change: "为注册表单增加校验",
      setup: "一个 Web 应用需要校验新注册表单的邮箱。仓库已有共享校验器，也遗留着一份表单内的局部实现。",
      task: "校验注册表单中的邮箱字段。", chose: "复制了遗留表单中的 validate_email 函数。",
      expects: "表单使用 shared/email_validator.py 负责的共享校验器。",
      observed: "共享实现和两个表单内函数被归入同一个 shadowed-abstraction 分组。",
      explanation: "Agent 参考了邻近代码，但仓库级证据表明，它制造了第三份邮箱校验；这项能力已经由 shared/email_validator.py 负责。",
      context: "仓库上下文：共享校验器与一个遗留局部实现已经并存；两份实现尚未达到检测阈值。",
    },
  },
  "typescript-helper-cycle": {
    language: "TypeScript", analysis: "Codebase", rule: "reforge.codebase.dependency_cycle", visualization: "cycle",
    beforeFiles: ["src/user_route.ts", "src/user_service.ts", "src/user_formatter.ts"], afterFiles: ["src/user_route.ts", "src/user_service.ts", "src/user_formatter.ts"],
    contextFiles: ["src/user_route.ts", "src/user_service.ts", "src/user_formatter.ts"], entry: "src/user_formatter.ts",
    relationships: [["src/user_route.ts", "src/user_service.ts"], ["src/user_service.ts", "src/user_formatter.ts"], ["src/user_formatter.ts", "src/user_route.ts"]],
    en: {
      title: "Reuses a helper, closes a loop", card: "The formatter imports back into the route", change: "Localize user display names",
      setup: "A small API needs localized user names. The request locale is already available as a helper in the HTTP route module.",
      task: "Format user display names according to the request locale.", chose: "Imported the Route's requestLocale helper into user_formatter.",
      expects: "Dependencies flow in one direction: route → service → formatter.",
      observed: "The reverse import closes a three-file cycle with three internal edges.",
      explanation: "Reusing the locale helper avoids local duplication, but its ownership is on the wrong side of the dependency direction and closes a repository-level loop.",
      context: "Repository context: before the patch, user_route depends on user_service, which depends on user_formatter; the formatter does not import back.",
    },
    "zh-CN": {
      title: "复用 Helper，形成依赖闭环", card: "Formatter 反向 Import Route", change: "本地化用户名显示",
      setup: "一个小型 API 需要按语言显示用户名。HTTP Route 模块中已经有读取请求语言的 Helper。",
      task: "根据请求语言格式化用户名。", chose: "在 user_formatter 中导入 Route 的 requestLocale Helper。",
      expects: "依赖保持单向：route → service → formatter。",
      observed: "反向 import 形成包含三个文件、三条内部边的依赖闭环。",
      explanation: "复用语言 Helper 避免了局部重复，但它位于错误的依赖方向上，最终闭合了仓库级循环。",
      context: "仓库上下文：修改前 user_route 依赖 user_service，user_service 依赖 user_formatter，而 formatter 不反向导入。",
    },
  },
};
