export const copy = {
  en: {
    language: "Language", docs: "Documentation", heroLabel: "Agent code, reviewed at repository scale", headline: "Fix the bad habits agents leave in your codebase.",
    intro: "The patch works. The tests pass. But the agent copied an old workaround, crossed a boundary, or bent dependencies around the task. Reforge finds the pattern behind the patch—and shows the evidence needed to fix it.",
    startReview: "See three agent habits ↓", fixtureNote: "Small, built-in repositories. Real analyzer output. Nothing is uploaded.",
    chooseLabel: "Three plausible patches. Three repository-level mistakes.", scenarios: "Choose the habit you want to inspect.", scenarioHelp: "Each example starts with a small agent task, then connects the patch to the wider pattern it damages.", openExample: "Inspect the evidence",
    selected: "Selected", nowReviewing: "Agent habit under review",
    maintainerTask: "The task", agentChose: "The agent habit", repositoryConflict: "Why it does not fit", reviewResult: "Repository evidence",
    generatedEvidence: "Real analyzer output", loadingReport: "Loading analyzer output…", evidenceShape: "Why Reforge flagged it", reportFacts: "Analyzer facts",
    technicalDetails: "Technical details", openReport: "Open the complete generated report", agentPatch: "Agent patch", patch: "Patch",
    repositoryContext: "Repository context", fullSource: "Full source", configuration: "Config", reproduce: "Command",
    commandNote: "Run from the Reforge repository after building the CLI.", footer: "Repository-owned fixtures. Real schema 27 reports. No uploads.",
    reportError: "The generated report could not be loaded. Patch, repository context, configuration, and local reproduction remain available.",
    threshold: "threshold", coverage: "coverage", exactWitness: "Exact ordered witness", source: "Source", sink: "Sink", step: "Step",
    implementationGroup: "Implementations grouped by the report", dependencyLoop: "Reported cycle members", beforeDirection: "Before: one-way dependency", afterDirection: "After: closed loop",
  },
  "zh-CN": {
    language: "语言", docs: "文档", heroLabel: "从整个仓库审查 Agent 代码", headline: "修掉 Agent 留在代码库里的坏习惯。",
    intro: "Patch 能跑，测试也通过；但 Agent 可能复制了旧权宜之计、越过已有边界，或为了眼前任务扭转依赖。Reforge 找出 Patch 背后的模式，并给出足以动手修正的证据。",
    startReview: "看看三种 Agent 坏习惯 ↓", fixtureNote: "内置小型仓库、真实分析器输出，不上传任何代码。",
    chooseLabel: "三个看似合理的 Patch，三个仓库级错误。", scenarios: "选择一种坏习惯，看看问题在哪。", scenarioHelp: "每个示例从一个小任务出发，再把 Patch 与它破坏的仓库级模式连起来。", openExample: "查看证据",
    selected: "已选择", nowReviewing: "正在审查的 Agent 习惯",
    maintainerTask: "任务", agentChose: "Agent 的坏习惯", repositoryConflict: "为什么不合适",
    reviewResult: "仓库级证据", generatedEvidence: "真实分析器输出", loadingReport: "正在载入分析器输出…", evidenceShape: "Reforge 为什么标记它", reportFacts: "分析器字段",
    technicalDetails: "技术细节", openReport: "打开完整生成报告", agentPatch: "Agent Patch", patch: "Patch",
    repositoryContext: "Repository context", fullSource: "Full source", configuration: "Config", reproduce: "Command",
    commandNote: "构建 CLI 后，从 Reforge 仓库根目录运行。", footer: "仓库自有 fixture、真实 schema 27 报告、不上传代码。",
    reportError: "无法载入生成的报告，但 patch、仓库上下文、配置和本地复现命令仍然可用。",
    threshold: "阈值", coverage: "覆盖", exactWitness: "精确有序 witness", source: "源点", sink: "汇点", step: "步骤",
    implementationGroup: "报告归组的实现", dependencyLoop: "报告中的闭环成员", beforeDirection: "修改前：单向依赖", afterDirection: "修改后：形成闭环",
  },
};

export const scenarios = {
  "typescript-service-bypass": {
    language: "TypeScript", analysis: "Dataflow", rule: "reforge.dataflow.adapter_flow_bypass", visualization: "witness",
    beforeFiles: ["src/user_route.ts", "src/user_service.ts", "src/database.ts"],
    afterFiles: ["src/user_route.ts", "src/user_search_route.ts", "src/user_service.ts", "src/database.ts"],
    contextFiles: ["src/user_route.ts", "src/user_service.ts", "src/database.ts"], entry: "src/user_search_route.ts",
    en: {
      habit: "Boundary shortcut",
      title: "Bypasses the service layer", card: "A new route queries the database directly", change: "Add a user search endpoint",
      setup: "A small API already sends user requests through a service layer. The new endpoint needs to look up a user by ID.",
      task: "Add an endpoint that looks up a user by ID.", chose: "Called queryUser directly from the new route.",
      expects: "HTTP routes call user_service before reaching the database module.",
      observed: "An exact value path reaches the database without crossing user_service.",
      explanation: "The endpoint works in isolation, but it creates a second route to the database and bypasses the repository's existing service boundary.",
      context: "Repository context (not a report field): the existing user route reaches database through user_service.",
    },
    "zh-CN": {
      habit: "绕过边界",
      title: "绕过 Service 层", card: "新 Route 直接查询数据库", change: "新增用户查询接口",
      setup: "一个小型 API 已经通过 Service 层处理用户请求。现在需要增加一个按 ID 查询用户的接口。",
      task: "增加一个按 ID 查询用户的接口。", chose: "在新的 Route 中直接调用 queryUser。",
      expects: "HTTP Route 先调用 user_service，再访问 database 模块。",
      observed: "一条精确值流路径没有经过 user_service，直接到达 database。",
      explanation: "这个接口单独看可以工作，却为数据库创建了第二条访问路径，绕过了仓库已有的 Service 边界。",
      context: "仓库上下文（并非报告字段）：已有用户 Route 通过 user_service 访问 database。",
    },
  },
  "python-duplicated-validation": {
    language: "Python", analysis: "Codebase", rule: "reforge.codebase.shadowed_abstraction", visualization: "group",
    beforeFiles: ["forms/legacy_email_validator.py", "shared/email_validator.py"],
    afterFiles: ["forms/legacy_email_validator.py", "forms/signup_email_validator.py", "shared/email_validator.py"],
    contextFiles: ["shared/email_validator.py", "forms/legacy_email_validator.py"], entry: "forms/signup_email_validator.py",
    en: {
      habit: "Copy and tweak",
      title: "Duplicates shared validation", card: "A third email validator appears", change: "Validate a signup form",
      setup: "A web app needs email validation on its new signup form. The repository already has a shared validator and one legacy local copy.",
      task: "Validate the email field on the signup form.", chose: "Copied the legacy form's local validate_email function.",
      expects: "Forms use the validator owned by shared/email_validator.py.",
      observed: "The shared implementation and two form-local functions form one shadowed-abstraction group.",
      explanation: "The Agent followed nearby code, but repository-wide evidence shows that this creates a third implementation of validation already owned by shared/email_validator.py.",
      context: "Repository context: a shared validator already exists alongside one legacy local implementation; two copies remain below the detector threshold.",
    },
    "zh-CN": {
      habit: "复制后微调",
      title: "重复共享校验逻辑", card: "出现第三份邮箱校验函数", change: "为注册表单增加校验",
      setup: "一个 Web 应用需要校验新注册表单的邮箱。仓库已有共享校验器，也遗留着一份表单内的局部实现。",
      task: "校验注册表单中的邮箱字段。", chose: "复制了遗留表单中的 validate_email 函数。",
      expects: "表单使用 shared/email_validator.py 负责的共享校验器。",
      observed: "共享实现和两个表单内函数被归入同一个 shadowed-abstraction 分组。",
      explanation: "Agent 参考了邻近代码，但仓库级证据表明，它制造了第三份邮箱校验；这项能力已经由 shared/email_validator.py 负责。",
      context: "仓库上下文：共享校验器与一个遗留局部实现已经并存；两份实现尚未达到检测阈值。",
    },
  },
  "typescript-helper-cycle": {
    language: "TypeScript", analysis: "Codebase", rule: "reforge.codebase.dependency_cycle", visualization: "cycle",
    beforeFiles: ["src/user_route.ts", "src/user_service.ts", "src/user_formatter.ts"], afterFiles: ["src/user_route.ts", "src/user_service.ts", "src/user_formatter.ts"],
    contextFiles: ["src/user_route.ts", "src/user_service.ts", "src/user_formatter.ts"], entry: "src/user_formatter.ts",
    relationships: [["src/user_route.ts", "src/user_service.ts"], ["src/user_service.ts", "src/user_formatter.ts"], ["src/user_formatter.ts", "src/user_route.ts"]],
    en: {
      habit: "Reuse at any cost",
      title: "Reuses a helper, closes a loop", card: "The formatter imports back into the route", change: "Localize user display names",
      setup: "A small API needs localized user names. The request locale is already available as a helper in the HTTP route module.",
      task: "Format user display names according to the request locale.", chose: "Imported the Route's requestLocale helper into user_formatter.",
      expects: "Dependencies flow in one direction: route → service → formatter.",
      observed: "The reverse import closes a three-file cycle with three internal edges.",
      explanation: "Reusing the locale helper avoids local duplication, but its ownership is on the wrong side of the dependency direction and closes a repository-level loop.",
      context: "Repository context: before the patch, user_route depends on user_service, which depends on user_formatter; the formatter does not import back.",
    },
    "zh-CN": {
      habit: "不计代价地复用",
      title: "复用 Helper，形成依赖闭环", card: "Formatter 反向 Import Route", change: "本地化用户名显示",
      setup: "一个小型 API 需要按语言显示用户名。HTTP Route 模块中已经有读取请求语言的 Helper。",
      task: "根据请求语言格式化用户名。", chose: "在 user_formatter 中导入 Route 的 requestLocale Helper。",
      expects: "依赖保持单向：route → service → formatter。",
      observed: "反向 import 形成包含三个文件、三条内部边的依赖闭环。",
      explanation: "复用语言 Helper 避免了局部重复，但它位于错误的依赖方向上，最终闭合了仓库级循环。",
      context: "仓库上下文：修改前 user_route 依赖 user_service，user_service 依赖 user_formatter，而 formatter 不反向导入。",
    },
  },
};
