export const copy = {
  en: {
    language: "Language", docs: "Documentation", headline: "The agent finished. Does the repository agree?",
    intro: "Review a plausible patch against the architecture and abstractions already present in its repository. Every finding below comes from Reforge.",
    chooseLabel: "Review queue", scenarios: "Choose a failure mode", maintainerTask: "Maintainer task", agentChose: "Agent chose",
    repositoryExpects: "Repository already expects", reforgeObserved: "Reforge observed", reviewResult: "Review result",
    generatedEvidence: "Generated evidence", loadingReport: "Loading generated evidence…", evidenceShape: "Evidence shape", reportFacts: "Report facts",
    technicalDetails: "Technical details", openReport: "Open full report", agentPatch: "Agent patch", patch: "Patch",
    repositoryContext: "Repository context", fullSource: "Full source", configuration: "Config", reproduce: "Command",
    commandNote: "Run from the Reforge repository after building the CLI.", footer: "Repository-owned fixtures. Real schema 27 reports. No uploads.",
    reportError: "The generated report could not be loaded. Patch, repository context, configuration, and local reproduction remain available.",
    threshold: "threshold", coverage: "coverage", exactWitness: "Exact ordered witness", source: "Source", sink: "Sink", step: "Step",
    implementationGroup: "Implementations grouped by the report", dependencyLoop: "Reported cycle members", beforeDirection: "Before: one-way dependency", afterDirection: "After: closed loop",
  },
  "zh-CN": {
    language: "语言", docs: "文档", headline: "Agent 写完了。仓库同意吗？",
    intro: "把一份看似合理的 patch 放回仓库已有架构与抽象中审查。下方每个结论都来自 Reforge 的真实报告。",
    chooseLabel: "审查队列", scenarios: "选择失败模式", maintainerTask: "Maintainer task｜维护者任务", agentChose: "Agent chose｜Agent 的选择",
    repositoryExpects: "Repository already expects｜仓库原有约定", reforgeObserved: "Reforge observed｜Reforge 观察",
    reviewResult: "审查结论", generatedEvidence: "生成的真实证据", loadingReport: "正在载入生成的证据…", evidenceShape: "证据结构", reportFacts: "报告字段",
    technicalDetails: "技术细节", openReport: "打开完整报告", agentPatch: "Agent patch", patch: "Patch",
    repositoryContext: "Repository context", fullSource: "Full source", configuration: "Config", reproduce: "Command",
    commandNote: "构建 CLI 后，从 Reforge 仓库根目录运行。", footer: "仓库自有 fixture、真实 schema 27 报告、不上传代码。",
    reportError: "无法载入生成的报告，但 patch、仓库上下文、配置和本地复现命令仍然可用。",
    threshold: "阈值", coverage: "覆盖", exactWitness: "精确有序 witness", source: "源点", sink: "汇点", step: "步骤",
    implementationGroup: "报告归组的实现", dependencyLoop: "报告中的闭环成员", beforeDirection: "修改前：单向依赖", afterDirection: "修改后：形成闭环",
  },
};

export const scenarios = {
  "typescript-boundary-bypass": {
    language: "TypeScript", analysis: "Dataflow", rule: "reforge.dataflow.adapter_flow_bypass", visualization: "witness",
    beforeFiles: ["src/application_checkout.ts", "src/payment_gateway.ts", "src/transport.ts"],
    afterFiles: ["src/application_checkout.ts", "src/application_refunds.ts", "src/payment_gateway.ts", "src/transport.ts"],
    contextFiles: ["src/application_checkout.ts", "src/payment_gateway.ts", "src/transport.ts"], entry: "src/application_refunds.ts",
    en: {
      title: "Bypasses an existing boundary", card: "A refund calls transport directly", change: "Add refund handling",
      task: "Add refund handling to the payment flow.", chose: "Called sendPayment directly from the new refund module.",
      expects: "Payment operations cross the payment_gateway adapter before reaching transport.",
      observed: "An exact value path reaches transport without crossing that adapter.",
      explanation: "The refund is locally straightforward, but it creates a second route to payment transport and bypasses the repository's existing gateway boundary.",
      context: "Repository context (not a report field): the existing charge path enters transport through payment_gateway.",
    },
    "zh-CN": {
      title: "绕过既有边界", card: "退款路径直接调用 transport", change: "增加退款处理",
      task: "为支付流程增加退款处理。", chose: "在新的退款模块中直接调用 sendPayment。",
      expects: "支付操作先经过 payment_gateway adapter，再到 transport。",
      observed: "一条精确值流路径未经过该 adapter，直接到达 transport。",
      explanation: "退款实现局部看起来很直接，却为支付 transport 创建了第二条入口，绕开了仓库已有的 gateway 边界。",
      context: "仓库上下文（并非报告字段）：已有扣款路径通过 payment_gateway 进入 transport。",
    },
  },
  "python-shadowed-abstraction": {
    language: "Python", analysis: "Codebase", rule: "reforge.codebase.shadowed_abstraction", visualization: "group",
    beforeFiles: ["providers/legacy_webhook_helper.py", "shared/event_normalizer.py"],
    afterFiles: ["providers/legacy_webhook_helper.py", "providers/orbit_webhook_helper.py", "shared/event_normalizer.py"],
    contextFiles: ["shared/event_normalizer.py", "providers/legacy_webhook_helper.py"], entry: "providers/orbit_webhook_helper.py",
    en: {
      title: "Duplicates repository capability", card: "A third event normalizer appears", change: "Add an Orbit webhook provider",
      task: "Add a webhook provider for Orbit.", chose: "Copied the neighboring provider's local normalization helper.",
      expects: "Webhook events use the shared event normalizer; one legacy provider still has a local copy.",
      observed: "The shared implementation and two local helpers form one shadowed-abstraction group.",
      explanation: "The agent followed nearby code, but repository-wide evidence shows that this creates a third implementation of a capability already owned by shared/event_normalizer.py.",
      context: "Repository context: a shared normalizer already exists alongside one legacy local implementation; two copies remain below the detector threshold.",
    },
    "zh-CN": {
      title: "复制仓库已有能力", card: "出现第三份 event normalizer", change: "增加 Orbit webhook provider",
      task: "增加 Orbit webhook provider。", chose: "照抄了邻近 provider 的局部 normalization helper。",
      expects: "Webhook event 使用共享 normalizer；只有一个遗留 provider 仍保留局部实现。",
      observed: "共享实现和两个局部 helper 被归入同一个 shadowed-abstraction 分组。",
      explanation: "Agent 跟随了邻近代码，但仓库级证据表明，它制造了第三份已有能力；该能力本应由 shared/event_normalizer.py 负责。",
      context: "仓库上下文：共享 normalizer 与一个遗留局部实现已经并存；两份实现尚未达到检测阈值。",
    },
  },
  "typescript-cycle": {
    language: "TypeScript", analysis: "Codebase", rule: "reforge.codebase.dependency_cycle", visualization: "cycle",
    beforeFiles: ["src/checkout.ts", "src/pricing.ts", "src/promotions.ts"], afterFiles: ["src/checkout.ts", "src/pricing.ts", "src/promotions.ts"],
    contextFiles: ["src/checkout.ts", "src/pricing.ts", "src/promotions.ts"], entry: "src/promotions.ts",
    relationships: [["src/checkout.ts", "src/pricing.ts"], ["src/pricing.ts", "src/promotions.ts"], ["src/promotions.ts", "src/checkout.ts"]],
    en: {
      title: "Fixes locally, closes a global loop", card: "A promotion imports back into checkout", change: "Add a first-order discount",
      task: "Add a first-order discount to promotions.", chose: "Imported checkout's order-history query helper into promotions.",
      expects: "Dependencies flow in one direction: checkout → pricing → promotions.",
      observed: "The reverse import closes a three-file cycle with three internal edges.",
      explanation: "Reusing the query helper avoids local duplication, but its ownership is on the wrong side of the dependency direction and closes a repository-level loop.",
      context: "Repository context: before the patch, checkout depends on pricing, which depends on promotions; promotions does not import back.",
    },
    "zh-CN": {
      title: "修复局部需求，制造全局闭环", card: "promotions 反向 import checkout", change: "增加首单优惠",
      task: "在 promotions 中增加首单优惠。", chose: "从 checkout 导入订单历史查询 helper。",
      expects: "依赖保持单向：checkout → pricing → promotions。",
      observed: "反向 import 形成包含三个文件、三条内部边的依赖闭环。",
      explanation: "复用查询 helper 避免了局部重复，但 helper 的归属位于错误的依赖方向上，最终闭合了仓库级循环。",
      context: "仓库上下文：修改前 checkout 依赖 pricing，pricing 依赖 promotions，而 promotions 不反向导入。",
    },
  },
};
