import { expect, test, type Page } from "@playwright/test";
import { pathToFileURL } from "node:url";
import { reportPath } from "./globalSetup";
const reportUrl=pathToFileURL(reportPath).href;
async function openReport(page:Page,hash=""){const errors:string[]=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));await page.goto(`${reportUrl}${hash}`);await expect(page.getByRole("heading",{name:"Refactoring evidence"})).toBeVisible();expect(errors).toEqual([])}
test("navigates evidence views without ranking concepts",async({page})=>{await openReport(page);for(const name of ["Evidence","Code map","Metrics","Coverage"]){await page.getByRole("tab",{name}).click();await expect(page.getByRole("tab",{name})).toHaveAttribute("aria-selected","true")}await expect(page.getByText(/priority|severity|hotspot|watchlist/i)).toHaveCount(0)});
test("restores evidence filters",async({page})=>{await openReport(page,"#evidence?query=main&kind=large_file&sort=path");await expect(page.getByLabel("Search evidence")).toHaveValue("main");await expect(page.getByLabel("Finding kind")).toHaveValue("large_file");await expect(page.getByLabel("Sort files")).toHaveValue("path");await page.reload();await expect(page.getByLabel("Search evidence")).toHaveValue("main")});
test("changes all evidence map layers and opens inspector",async({page})=>{await openReport(page,"#map");for(const layer of ["Issues","Churn","Coverage","Findings"]){await page.getByRole("button",{name:layer,exact:true}).click()}const map=page.getByRole("group",{name:/repository map/i});await map.getByRole("button").first().click();await expect(page.getByRole("complementary",{name:"File inspector"})).toBeVisible();await expect(page.getByRole("heading",{name:"Test reachability"})).toBeVisible()});
test("has no horizontal overflow on mobile",async({page})=>{await page.setViewportSize({width:390,height:844});await openReport(page);const widths=await page.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth]);expect(widths[0]).toBeLessThanOrEqual(widths[1])});
